Shutters:
  1: "In"
  2: "Ga"
  3: ""
  4: "Si"
  5: ""
  6: "Al"
  7: ""
  8: ""
  9: ""
  10: ""
  11: "Be"
  12: ""
  13: ""
  14: ""
  15: ""
  16: ""
Sources:
  1: "In 1 Верх"
  2: "In 1 Низ"
  3: "Ga 1 Верх"
  4: "Ga 1 Низ"
  5: ""
  6: ""
  7: "Si"
  8: "CBr4"
  9: "Al 1 Верх"
  10: "Al 1 Низ"
  11: ""
  12: ""
  13: ""
  14: ""
  15: "As Tip"
  16: "As Bulk"
  17: ""
  18: "Be"
  19: ""
  20: ""
  21: "РМ"
  22: "КО"
  23: ""
  24: ""
  25: ""
  26: ""
  27: ""
  28: ""
  29: ""
  30: ""
  31: ""
  32: ""
ChamberHeaters:
  1: "ТЭН упр."
  2: "КР датч.1"
  3: "КР датч.2"
  4: "КР шибер1"
  5: "КР шибер2"
  6: "КР ион."
  7: "КШ"
  8: "КШ ион."
  9: "КО"
  10: "КО ион."
  11: "Роб. в. упр."
  12: ""
  13: "КХ"
  14: "Роб. н. упр."
  15: "КИСО"
  16: "Роб. ион."
Waters:
  1: ""
  2: "Be и вент. As"
  3: "In рубашка"
  4: "In фланец и Ga"
  5: "Al и Si рубашки"
  6: "Al фланец и Be руб."
  7: "КШ"
  8: ""
  9: "Турбина КР"
  10: ""
  11: ""
  12: ""
  13: ""
  14: ""
  15: ""
  16: ""
Gases:
  1: ""
  2: "Be и вент. As"
  3: "In рубашка"
  4: "In фланец и Ga"
  5: "Al и Si рубашки"
  6: "Al фланец и Be руб."
  7: "КШ"
  8: ""
  9: "Турбина КР"
  10: ""
  11: ""
  12: ""
  13: ""
  14: ""
  15: ""
  16: ""
